use strict;
use warnings;
no warnings qw(once redefine);
use FindBin qw($Bin);
use Test::More;
do "$Bin/../usr/bin/meter_lg_3d_autocal.pl";die $@ if $@;
my @order;
local *main::write_state=sub {1};
local *main::log_line=sub {};
local *main::fixture_reading_for_step=sub {push @order,'measurement';{X=>1,Y=>1,Z=>1}};
my $wrong=0;
local *main::api_json=sub {
 push @order,$_[1];
 return {status=>'ok',calibration_mode=>0} if $_[1] eq '/api/lg/status';
 return {status=>'ok',picture_settings=>{pictureMode=>$wrong?'hdrFilmMaker':'hdrCinema',smoothGradation=>'off'}};
};
my $config={picture_mode=>'hdrCinema',signal_mode=>'hdr10',automation_processing_settings=>{smoothGradation=>'off'}};
my $state={};
my ($reading,$error)=main::read_step($config,{},$state);
ok($reading&&!$error,'read can proceed after successful guard');
is_deeply(\@order,['/api/lg/status','/api/lg/picture-settings','measurement'],'settings are checked before any measurement');
@order=();main::read_step($config,{},$state);
is_deeply(\@order,['measurement'],'unchanged calibration state avoids repeated per-patch checks');
$main::LG_3D_SETTINGS_EPOCH++;$wrong=1;@order=();
($reading,$error)=main::read_step($config,{},$state);
ok(!$reading,'new transition with wrong mode cannot produce a measurement');
like($error,qr/picture mode differs/,'actual guard error reaches worker measurement failure');
ok(!grep {$_ eq 'measurement'} @order,'meter is never called for wrong mode');
done_testing();
