use strict;
use warnings;
no warnings 'once';
use FindBin qw($Bin);
use File::Temp qw(tempdir);
use Test::More;
require "$Bin/../usr/share/PGenerator/webui.pm";
local $ENV{PGEN_AUTOMATION_DIR}=tempdir(CLEANUP=>1);
PGAutomation::ensure_store();
my @observed;
my $fail=0;
my $connected=1;
my $calibration_on=0;
my $exit_ok=1;
my $exit_calls=0;
{
 no warnings 'redefine';
 local *main::webui_lg_status_json=sub { return PGAutomation::encode_json({paired=>1,connected=>$connected,disconnected=>!$connected,software_version=>'test',calibration_mode=>$calibration_on}); };
 local *main::webui_lg_calibration_mode=sub {
  $exit_calls++;
  my $body=PGAutomation::decode_json($_[0]);
  ok(!$body->{enabled},'preflight only closes calibration mode, never opens it');
  like(main::webui_automation_preflight_status()->{message},qr/calibration mode/,'calibration exit progress is persisted before the TV request');
  return PGAutomation::encode_json($exit_ok?{status=>'ok',calibration_mode=>0}:{status=>'error',message=>'CAL_END rejected'});
 };
 local *main::webui_meter_status=sub { return PGAutomation::encode_json({detected=>1}); };
 local *main::webui_meter_series_alive=sub {0};
 local *main::webui_meter_lg_autocal_running=sub {0};
 local *main::webui_meter_lg_3d_autocal_running=sub {0};
 local *main::webui_meter_lg_dv_profile_running=sub {0};
 local *main::webui_meter_session_alive=sub {0};
 local *main::webui_lg_connect=sub {PGAutomation::encode_json({status=>'error',message=>'TV offline'})};
 local *main::webui_lg_picture_settings=sub {
  die 'TV connection lost' if $fail;
  my $request=PGAutomation::decode_json($_[0]);
  push @observed,main::webui_automation_preflight_status();
  my @keys=grep {$_ ne 'unsupportedPin'} @{$request->{keys}};
  return PGAutomation::encode_json({status=>'ok',current_input=>'hdmi1',generation_profile=>{capability_library_valid=>1,capability_platform_profile_applied=>1,capability_profile_id=>'test-g3',capability_profile_hash=>('a'x64)},lg_generation=>{model_name=>'OLED55G36LA',generation_id=>'lg2022plus_oled',platform_year=>2023},supported_picture_keys=>\@keys,picture_settings=>{map {$_=>'off'} @keys},unsupported_picture_keys=>{unsupportedPin=>'TV rejected this control'}});
 };
 my $job={name=>'SDR reference',signal_format=>'sdr',picture_mode=>'filmMaker',template_id=>'reference-settings-v1',settings=>{truMotionMode=>'off',contrast=>85},stages=>{pre_readings=>1,calibration=>1,post_readings=>1}};
 my $batch=main::webui_automation_checked_readiness({items=>[$job,{%$job,settings=>{contrast=>100},signal_format=>'hdr10',picture_mode=>'hdrCinema'}, {%$job,settings=>{contrast=>100},signal_format=>'dv',picture_mode=>'dolbyVisionCinema'}]},'start');
 ok($batch->{ready},'mixed-format batch passes general readiness and static validation');
 is(scalar @observed,0,'batch startup never probes picture settings for pending modes');
 is(scalar @{$batch->{items}},3,'all pending jobs survive static validation');
 ok(!grep({$_->{name}=~/generation|tv-reachable|key-contrast|hazard-/} @{$batch->{checks}}),'batch does not imply TV control support has already been checked');
 like($batch->{message},qr/checked at each job/,'startup explains deferred hardware checks');
 is($batch->{items}[1]{settings}{brightness},50,'HDR AutoCal injects the essential brightness recipe');
 is($batch->{items}[1]{settings}{hdrDynamicToneMapping},'off','HDR AutoCal injects the essential tone-mapping recipe');
 my $conflict=main::webui_automation_checked_readiness({items=>[{%$job,signal_format=>'hdr10',picture_mode=>'hdrCinema'}]},'start');
 ok(!$conflict->{ready},'SDR contrast pinned on an HDR AutoCal job is rejected');
 is($conflict->{items}[0]{settings}{contrast},85,'conflicting explicit setting is preserved for correction');
 my $invalid=main::webui_automation_checked_readiness({items=>[{%$job,signal_format=>'hlg',picture_mode=>'hdrCinema'}]},'start');
 ok(!$invalid->{ready},'unsupported HLG calibration still blocks startup without TV probes');
 is(scalar @observed,0,'invalid queue does not probe inactive settings');
 for my $case (['hdr10','hdrCinema'],['dv','dolbyVisionFilmMaker']) {
  my $bad_target=main::webui_automation_checked_readiness({items=>[{%$job,template_id=>'',signal_format=>$case->[0],picture_mode=>$case->[1],settings=>{},panel_light=>{policy=>'target',key=>'backlight',target_luminance=>100}}]},'start');
  ok(!$bad_target->{ready},"$case->[0] target policy is rejected before hardware work");
  my ($check)=grep {$_->{name} eq 'item-0-panel-light-signal'} @{$bad_target->{checks}};
  like($check->{message},qr/SDR-only.*panel_light\.policy: fixed/,'API rejection explains the supported format and fixed alternative');
 }
 my $home={%$job,signal_format=>'hdr10',picture_mode=>'hdrCinemaBright'};
 my $unsupported=main::webui_automation_checked_readiness({items=>[$home]},'start');
 ok(!$unsupported->{ready},'HDR Cinema Home AutoCal is blocked at batch startup');
 like(join(' ',map {$_->{message}} grep {!$_->{ok}} @{$unsupported->{checks}}),qr/hdrCinemaBright is not a supported LG AutoCal.*No alternative picture mode/,'unsupported mode explains the required explicit choice');
 is(scalar @observed,0,'unsupported mode is caught without probing or switching pending modes');
 is($unsupported->{items}[0]{picture_mode},'hdrCinemaBright','unsupported mode is never silently substituted');
 my $readings=main::webui_automation_checked_readiness({items=>[{%$home,stages=>{pre_readings=>1,calibration=>0,post_readings=>0}}]},'start');
 ok($readings->{ready},'HDR Cinema Home remains available for measurements without AutoCal');
 ok(main::webui_automation_calibration_mode_ok('dolbyVisionCinemaBright'),'Dolby Vision Cinema Home remains supported');
 ok(!main::webui_automation_calibration_mode_ok('hdr_cinema_home'),'HDR Home aliases are also rejected');
 {
  my $reader=\&main::webui_lg_picture_settings;
  my $signal='sdr';my $mode='filmMaker';my @probes;
  local *main::webui_pattern_signal_mode=sub {$signal};
  local *main::webui_lg_picture_settings=sub {
   my $request=PGAutomation::decode_json($_[0]);push @probes,$request;
   my $result=PGAutomation::decode_json($reader->($_[0]));
   $result->{picture_settings}{pictureMode}=$mode;
   return PGAutomation::encode_json($result);
  };
  my $preview=main::webui_automation_checked_readiness({scope=>'preview',items=>[$job,{%$job,settings=>{contrast=>100},signal_format=>'hdr10',picture_mode=>'hdrCinema'}]},'readiness');
  ok($preview->{ready},'preview probes first job in the matching active context');
  ok(!grep({($_->{signal_mode}||'') eq 'hdr10'} @probes),'preview never probes inactive later signal');
  like($preview->{message},qr/later jobs still require/,'preview does not certify the full queue TV settings');
  @probes=();$signal='dv';
  $preview=main::webui_automation_checked_readiness({scope=>'preview',items=>[$job]},'readiness');
  ok(!$preview->{ready},'wrong generator signal blocks preview');
  is(scalar @probes,0,'no picture settings probe in the wrong signal');
  $signal='sdr';$mode='cinema';@probes=();
  $preview=main::webui_automation_checked_readiness({scope=>'preview',items=>[$job]},'readiness');
  ok(!$preview->{ready},'wrong live picture mode blocks preview');
  is(scalar @probes,1,'only context is read on picture-mode mismatch');
  ok(!exists($probes[0]{picture_mode}),'context read cannot echo a requested virtual mode');
 }
 my $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job,$job],queue_name=>'Six modes',request_id=>'test-check'},'start');
 ok($result->{ready},'known reference motion pin is upgraded without blocking startup');
 ok(grep({$_->{name} eq 'calibration-mode-off' && $_->{ok}} @{$result->{checks}}),'readiness includes a fresh TV exit acknowledgement even when cached flag is off');
 ok(!exists $result->{items}[0]{settings}{truMotionMode},'unsupported reference pin is removed');
 ok(grep({$_->{level} eq 'warning' && $_->{message}=~/TruMotion/} @{$result->{checks}}),'manual motion check is an explicit warning');
 is(main::webui_automation_preflight_status()->{status},'ready','successful checks persist ready status');
 is(scalar @{main::webui_automation_preflight_status()->{checks}},scalar @{$result->{checks}},'all startup checks are saved for the scrollable log');
 ok($result->{checks}[0]{time}>0,'startup checks record real timestamps');
 my $events=main::webui_automation_preflight_status()->{events};
 is_deeply($result->{events},$events,'startup milestones returned for saving with the run');
 ok(grep({$_->{message}=~/Checking TV settings for/ && $_->{item_number}==1} @$events),'job-start milestones survive after checks complete');
 ok(!grep({$_->{message}=~/Checking autoPowerOff/} @$events),'individual hazard probes do not flood milestone log');
 ok(grep({grep({$_->{message}=~/Checking TV settings for/} @{$_->{events}||[]})} @observed),'milestones are saved before slow TV settings requests');
 is(main::webui_automation_preflight_status()->{id},'test-check','request correlation is retained');
 ok(grep({$_->{status} eq 'checking' && $_->{active_item}==1} @observed),'another reader can observe job-two progress during a TV request');
 ok(grep({$_->{message}=~/autoPowerOff/} @observed),'individual TV hazard controls are visible during probing');
 $job->{settings}{unsupportedPin}='on';
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job],request_id=>'blocked'},'start');
 ok(!$result->{ready},'unknown explicit pin still blocks, rather than being silently dropped');
 my $state=main::webui_automation_preflight_status();
 is($state->{status},'blocked','failed startup is retained without a calibration runner');
 like(join(' ',map {$_->{message}} @{$state->{issues}}),qr/unsupportedPin.*TV rejected this control.*Configure/,'failure names the control, TV response and corrective action');
 is($state->{items}[0]{status},'blocked','failed job is marked blocked');
 main::webui_automation_preflight_finish('failed','Runner failed to launch','runner-start-failed','run-test');
 $state=main::webui_automation_preflight_status();
 is($state->{error_code},'runner-start-failed','launch failure is durable');
 is($state->{events}[-1]{message},'Runner failed to launch','launch failure is saved in the activity timeline');
 is($state->{events}[-1]{level},'error','launch failure has error severity');
 is($state->{run_id},'run-test','last run remains discoverable when its execution claim ends');
 $fail=1;
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 ok(grep({$_->{name}=~/tv-reachable/ && !$_->{ok}} @{$result->{checks}}),'TV read failure is reported');
 ok(!grep({$_->{name}=~/key-/ && !$_->{ok}} @{$result->{checks}}),'failed reads do not invent unsupported-control errors');
 $connected=0;my $before=@observed;my $exits_before=$exit_calls;
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 is(scalar(@observed),$before,'disconnected TV is rejected before per-job probing');
 is($exit_calls,$exits_before,'offline readiness does not attempt calibration exit');
 is(main::webui_automation_preflight_status()->{items}[0]{status},'queued','unattempted job is not presented as checked');
 is(scalar(grep {$_->{level} eq 'error'} @{$result->{checks}}),1,'one connection failure has one actionable error');
 like(join(' ',map {$_->{message}} @{$result->{checks}}),qr/paired, but reconnecting failed: TV offline/,'offline error distinguishes saved pairing from connection failure');
 $fail=0;delete $job->{settings}{unsupportedPin};
 my $reconnects=0;
 local *main::webui_lg_connect=sub {
  $reconnects++;
  like(main::webui_automation_preflight_status()->{message},qr/Reconnecting.*saved key/,'reconnect progress is visible before the connection request');
  PGAutomation::encode_json({status=>'ok',paired=>1,connected=>1,disconnected=>0});
 };
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 ok($result->{ready},'new queue readiness reconnects and continues through per-job checks');
 is($reconnects,1,'one bounded saved-pairing reconnect');
 $connected=1;$calibration_on=1;
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 ok(grep({$_->{name} eq 'calibration-mode-off' && $_->{message}=~/showed calibration mode on.*acknowledged exit/} @{$result->{checks}}),'stale calibration mode is corrected and reported');
 $exit_ok=0;$before=@observed;
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 ok(!$result->{ready},'failed TV exit blocks startup');
 is(scalar(@observed),$before,'unconfirmed calibration mode prevents baseline settings probes');
 like(join(' ',map {$_->{message}} @{$result->{checks}}),qr/CAL_END rejected/,'startup exposes the actual exit failure reason');
 $exits_before=$exit_calls;
 local *main::webui_meter_session_alive=sub {1};
 $result=main::webui_automation_checked_readiness({scope=>'job',items=>[$job]},'start');
 ok(!$result->{ready},'active standalone meter session still blocks readiness');
 is($exit_calls,$exits_before,'busy meter checks prevent closing another operation calibration session');
 is($reconnects,1,'does not reconnect over an unrelated meter operation');
}
{
 no warnings 'redefine';
 local *main::webui_automation_readiness_data=sub {die 'Unexpected readiness exception'};
 my $result=main::webui_automation_checked_readiness({scope=>'job',items=>[]},'start');
 is($result->{error_code},'preflight-error','unexpected exception produces structured error');
 like(main::webui_automation_preflight_status()->{message},qr/Unexpected readiness exception/,'exception is visible after reload');
 like($result->{events}[-1]{message},qr/Unexpected readiness exception/,'exception also appears in the saved log');
}
{
 my $state={};
 main::webui_automation_preflight_event($state,'Checking TV',0);
 main::webui_automation_preflight_event($state,'Checking TV',0);
 is(scalar @{$state->{events}},1,'identical consecutive milestones are deduplicated');
 main::webui_automation_preflight_event($state,'Checking TV',1);
 is(scalar @{$state->{events}},2,'different jobs keep their own milestones');
 main::webui_automation_preflight_event($state,"Step $_",1) for 1..220;
 is(scalar @{$state->{events}},200,'startup milestones are bounded');
 is($state->{events}[-1]{message},'Step 220','bounded log retains latest milestone');
}
PGAutomation::write_json_atomic(PGAutomation::base_dir().'/preflight.json',{status=>'checking',started_at=>PGAutomation::now()-200,updated_at=>PGAutomation::now()-150});
is(main::webui_automation_preflight_status()->{status},'interrupted','stale startup does not claim healthy progress');
my $custom=main::webui_automation_normalize_item({settings=>{truMotionMode=>'off'}});
ok(exists $custom->{settings}{truMotionMode},'non-reference user settings are never silently removed');
my $override=main::webui_automation_normalize_item({template_id=>'reference-settings-v1',settings=>{truMotionMode=>'smooth'}});
is($override->{settings}{truMotionMode},'smooth','explicit nondefault reference override is preserved for validation');
my $hdr=main::webui_automation_normalize_item({template_id=>'reference-settings-v1',signal_format=>'hdr10',settings=>{}});
is($hdr->{settings}{hdrDynamicToneMapping},'off','HDR reference uses the confirmed tone-mapping key');
my $summary=main::webui_automation_public_run({status=>'failed',active_item=>0,items=>[{name=>'SDR',status=>'failed',failure=>{stage=>'greyscale-done',message=>'Meter disconnected'},warnings=>['Target not reached']}]});
is($summary->{items}[0]{failure}{message},'Meter disconnected','live summary preserves job-specific failure');
is($summary->{items}[0]{warnings}[0],'Target not reached','live summary preserves warnings');
File::Path::make_path(PGAutomation::run_dir('last-failed'));
PGAutomation::write_json_atomic(PGAutomation::run_dir('last-failed').'/run.json',{id=>'last-failed',status=>'failed',items=>[],failure=>{stage=>'meter-read',message=>'USB disconnected'}});
PGAutomation::write_json_atomic(PGAutomation::base_dir().'/preflight.json',{status=>'started',run_id=>'last-failed',updated_at=>PGAutomation::now()});
my $status=PGAutomation::decode_json(main::webui_automation_api('/api/automation/runs/current','GET',''));
is($status->{run}{failure}{message},'USB disconnected','terminal failure is still returned after the execution claim is gone');
is($status->{preflight}{status},'started','status API exposes persisted startup state');
{
 no warnings 'redefine';
 my $connects=0;my $connected=0;my $paired=1;my $available=1;
 local *main::webui_automation_read_execution=sub {{run_id=>'resume-test',token=>'saved-token'}};
 local *main::webui_lg_status_json=sub {PGAutomation::encode_json({connected=>$connected,disconnected=>!$connected,paired=>$paired})};
 local *main::webui_lg_connect=sub {$connects++;PGAutomation::encode_json({status=>$available?'ok':'error',connected=>$available,message=>'TV offline'})};
 my $run={id=>'resume-test',token=>'saved-token'};
 is(main::webui_automation_reconnect_for_resume($run)->{status},'ok','Resume reconnects the paired TV after a service restart');
 is($connects,1,'Resume uses the saved pairing once');
 $connected=1;
 is(main::webui_automation_reconnect_for_resume($run)->{status},'ok','already connected TV is retained');
 is($connects,1,'no unnecessary reconnect during Resume');
 $connected=0;$available=0;
 like(main::webui_automation_reconnect_for_resume($run)->{message},qr/TV offline.*retry Resume/,'failed reconnect tells the user what happened and what to do');
 $paired=0;
 is(main::webui_automation_reconnect_for_resume($run)->{error_code},'tv-not-paired','Resume never initiates new pairing');
 is(main::webui_automation_reconnect_for_resume({%$run,token=>'wrong'})->{error_code},'automation-owner-mismatch','another owner cannot trigger reconnect');
 is($connects,2,'unpaired or mismatched owner makes no connection attempt');
}
{
 no warnings 'redefine';
 my $calls=0;my $execution;
 local *main::webui_automation_read_execution=sub {$execution};
 local *main::webui_lg_connect=sub {$calls++;PGAutomation::encode_json({status=>'ok',connected=>1,paired=>1})};
 is(main::webui_automation_reconnect_for_readiness({paired=>0},'')->{error_code},'tv-not-paired','missing pairing requires explicit pairing');
 is($calls,0,'unpaired TV is never connected automatically');
 is(main::webui_automation_reconnect_for_readiness({paired=>1,connected=>1},'')->{status},'ok','connected TV needs no reconnect');
 is($calls,0,'connected TV remains untouched');
 $execution={status=>'running',token=>'owner-token'};
 is(main::webui_automation_reconnect_for_readiness({paired=>1,disconnected=>1},'wrong')->{error_code},'automation-active','other run ownership blocks reconnect');
 is($calls,0,'no connection when ownership mismatches');
 is(main::webui_automation_reconnect_for_readiness({paired=>1,disconnected=>1},'owner-token')->{status},'ok','owning runner may reconnect');
 is($calls,1,'owning runner reuses saved pairing once');
}
done_testing();
