use strict;
use warnings;
use FindBin qw($Bin);
use Test::More;
my $node=`sh -c 'command -v node || command -v nodejs' 2>/dev/null`;chomp $node;
plan skip_all=>'Node is not installed' if !$node;
my $output=`"$node" "$Bin/js/automation_readiness_queue_match.js" 2>&1`;
is($?,0,'readiness queue matching and save release checks pass') or diag $output;
like($output,qr/^PASS automation readiness queue match and save release/m,'P1 and P8 behaviour exercised');
done_testing();
