use strict;
use warnings;
no warnings qw(redefine once);
use FindBin qw($Bin);
use Test::More;
do "$Bin/../usr/bin/meter_lg_autocal.pl"; die $@ if $@;
my (@saved,@logs);
local *main::write_state=sub {push @saved,$_[0]{activity_sequence}};
local *main::log_line=sub {push @logs,$_[0]};
my $state={};
main::autocal_activity_reading($state,'7%',4,8,0.61,0.82,0.5,2.1,2);
like($logs[-1],qr/7% \| Attempt 4\/8 \| dE 0.610; target <=0.50; previous best 0.820/,'point, attempt, error, target and comparison are explicit');
like($logs[-1],qr/Y 2.1000 cd\/m2; luminance error \+5.0%/,'luminance error has direction and units');
unlike($logs[-1],qr/upload|applied|verified/,'a measurement does not claim an adjustment');
main::autocal_activity_reading($state,'1%',1,8,undef,undef,0.75,0,1,0.5);
like($logs[-1],qr/dE unavailable/,'missing delta E is not fabricated as zero');
like($logs[-1],qr/requested target 0.50 \(near-black allowance active\)/,'effective solver allowance cannot masquerade as the requested target');
like($logs[-1],qr/luminance error -100.0%/,'zero luminance is a real value');
my @curve=(0)x3072;@curve[7,1031,2055]=(105,198,300);
main::autocal_activity_upload($state,'7%',4,[100,200,300],\@curve,7,1);
like($logs[-1],qr/LUT upload accepted \| LUT codes: R 100->105, G 200->198, B 300->300 \| Not yet measured/,'actual channel codes and acknowledgement are distinct from measured success');
main::autocal_activity_upload($state,'7%',5,[100,200,300],\@curve,7,0);
like($logs[-1],qr/LUT upload failed/,'failed upload stays explicit');
unlike($logs[-1],qr/accepted|Not yet measured/,'failed upload does not claim acceptance');
{
 my $uncertain={};
 main::autocal_activity_upload($uncertain,'7%',6,[undef,undef,undef],\@curve,7,1);
 like($logs[-1],qr/R unknown->105/,'an in-memory revert or failed prior write cannot invent the TV previous value');
 pop @logs;pop @saved;
}
main::autocal_activity_event($state,"Restore best\nNo fresh reading");
is($logs[-1],'Restore best No fresh reading','one event cannot inject extra log lines');
main::autocal_activity_event($state,"event $_") for 1..100;
is(scalar @{$state->{activity_events}},64,'status buffer is bounded');
is($state->{activity_events}[-1]{seq},105,'sequence remains monotonic after eviction');
is($state->{activity_events}[0]{seq},42,'oldest retained sequence identifies gaps');
is(scalar @saved,105,'each event reaches status immediately');
is(scalar @logs,105,'standalone worker log retains all events');
ok($state->{activity_events}[-1]{time}>0,'events have worker timestamps');
main::autocal_activity_point_finished($state,'80%','finished',.410,.074);
like($logs[-1],qr/Point finished \| Accepted refinement dE 0\.074/,'accepted extra refinement reports its own measurement');
unlike($logs[-1],qr/0\.410/,'earlier best cannot masquerade as the accepted refinement');
main::autocal_activity_point_finished($state,'80%','finished',.410);
like($logs[-1],qr/Best measured dE 0\.410/,'ordinary best-curve reporting is unchanged');
main::autocal_activity_point_finished($state,'80%','failed',undef);
like($logs[-1],qr/Point failed \| No usable result/,'failed point cannot invent a measurement');
done_testing();
