use strict;
use warnings;
use FindBin qw($Bin);
use Test::More;
my $node=`sh -c 'command -v node || command -v nodejs' 2>/dev/null`;chomp $node;
plan skip_all=>'Node is not installed' if !$node;
my $output=`"$node" "$Bin/js/chart_labels_and_progress.js" 2>&1`;
is($?,0,'chart label, gamma clip and progress label regression checks pass') or diag $output;
like($output,qr/^PASS chart labels and progress/m,'HDR clip, EOTF title and held labels exercised');
done_testing();
