use strict;
use warnings;
use FindBin qw($Bin);
use Test::More;
my $node=`sh -c 'command -v node || command -v nodejs' 2>/dev/null`;chomp $node;
plan skip_all=>'Node is not installed' if !$node;
my $output=`"$node" "$Bin/js/series_cache_quota.js" 2>&1`;
is($?,0,'series cache quota regression checks pass') or diag $output;
like($output,qr/^PASS series cache quota/m,'report suspension, eviction order and draft retry exercised');
done_testing();
