ip_pattern=0.0.0.0
port_pattern=85
rgb_quant_range=1
dv_color_space=0
dv_metadata=0
eotf=0
max_cll=1000
max_fall=400
max_luma=1000
min_luma=0.005
color_format=0
colorimetry=0
dv_interface=1
dv_map_mode=2
dv_status=0
is_hdr=0
is_ll_dovi=0
is_sdr=1
is_std_dovi=0
max_bpc=8
mode_idx=20
primaries=0
